version: "3.8"
services:
  db:
    image: postgres:16-alpine
    container_name: todo-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - todo_db_data:/var/lib/postgresql/data

volumes:
  todo_db_data:
